stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/


lint:
  stage: lint
  image: node:latest
  before_script:
    - npm install
  script:
    - NODE_ENV=mock npm run lint

test:
  stage: test
  image: node:latest
  before_script:
    - npm install
  script:
    - NODE_ENV=mock npm run test

variables:
  DOCKER_TLS_CERTDIR: ""
  #LATEST_VER: s4ng/cicd-dino:latest

build:
  stage: build
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master