default:
  image: node:latest

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

install-dependency:
  stage: .pre
  script:
    - npm install

lint:
  stage: lint
  script:
    - NODE_ENV=mock npm run lint

test:
  stage: test
  script:
    - NODE_ENV=mock npm run test

deploy-prod:
  stage: deploy
  script:
    - echo "deploy"