stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/


lint:
  stage: lint
  image: node:latest
  before_script:
    - npm install
  script:
    - NODE_ENV=mock npm run lint

test:
  stage: test
  image: node:latest
  before_script:
    - npm install
  script:
    - NODE_ENV=mock npm run test

variables:
  DOCKER_TLS_CERTDIR: ""
  LATEST_VER: s4ng/cicd-dino:latest

build:
  stage: build
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  script:
    - docker info
    - docker build --pull -t $LATEST_VER .
  only:
    - master

push:
  stage: build
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push $LATEST_VER && docker image rm $LATEST_VER
  only:
    - master