stages:
  - lint
  - test
  - build

cache:
  paths:
    - node_modules/

install-dependency:
  stage: .pre
  image: node:latest
  script:
    - npm install

lint:
  stage: lint
  image: node:latest
  script:
    - NODE_ENV=mock npm run lint

test:
  stage: test
  image: node:latest
  script:
    - NODE_ENV=mock npm run test

variables:
  DOCKER_TLS_CERTDIR: ""

prebuild:
  stage: build
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  script:
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_IMAGE"
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build:
  stage: build
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master